src/Entity/ShopProduct.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
/**
 * @ORM\Entity(repositoryClass="App\Repository\ShopProductRepository")
 */
class ShopProduct
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(length=255, unique=true)
     * @Assert\NotBlank()
     * @Assert\Length(max=254)
     */
    private $name;
//     * @Assert\Regex(pattern="/^[a-zA-Z0-9_]+$/")

    /**
     * @var ShopCategory
     * @ORM\ManyToOne(targetEntity="ShopCategory", inversedBy="products")
     */
    private $category;


    /**
     * @var double
     * @ORM\Column(type="decimal", precision=7, scale=2)
     */
    private $price;

    /**
     * @var boolean
     * @ORM\Column(type="boolean")
     */
    private $recommendedProduct;
    /**
     * @var string
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @var string
     * @ORM\Column(length=255)
     * @Assert\NotBlank()
     * @Assert\Length(max=254)
     */
    private $producent;


    /**
     * @var string
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $productFeatures;


    /**
     * @Vich\UploadableField(mapping="product_images", fileNameProperty="imageFile")
     * @Assert\Image(
     *     detectCorrupted=true,
     *     allowLandscape=true,
     *     allowSquare=false,
     *     minWidth = 100,
     *     maxWidth = 100,
     *     minHeight = 200,
     *     maxHeight = 200,
     *     maxSize="1M"
     * )
     */
    private $imageFile;


    /**
     * @Vich\UploadableField(mapping="product_images", fileNameProperty="imageFileBigger")
     * @Assert\Image(
     *     detectCorrupted=true,
     *     allowLandscape=true,
     *     allowSquare=false,
     *     minWidth = 200,
     *     maxWidth = 200,
     *     minHeight = 400,
     *     maxHeight = 400,
     *     maxSize="1M"
     * )
     */
    private $imageFileBigger;

    /**
     * @ORM\Column(type="text")
     * @var string
     */
    private $image;

    /**
     * @ORM\Column(type="text")
     * @var string
     */
    private $icon;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    private $uploadUpdatedAt;

    /**
     * @var integer
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     */
    private $quantity;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ShopCartItem", mappedBy="product")
     */
    private $shopCartItems;

    public function __construct()
    {
        $this->shopCartItems = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return ShopCategory
     */
    public function getCategory(): ?ShopCategory
    {
        return $this->category;
    }

    /**
     * @param ShopCategory $category
     */
    public function setCategory(ShopCategory $category): void
    {
        $this->category = $category;
    }

    /**
     * @return float
     */
    public function getPrice(): ?float
    {
        return $this->price;
    }

    /**
     * @param float $price
     */
    public function setPrice(float $price): void
    {
        $this->price = $price;
    }

    /**
     * @return string
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * @return string
     */
    public function getProducent(): ?string
    {
        return $this->producent;
    }

    /**
     * @param string $producent
     */
    public function setProducent(string $producent): void
    {
        $this->producent = $producent;
    }

    /**
     * @return string
     */
    public function getProductFeatures(): ?string
    {
        return $this->productFeatures;
    }

    /**
     * @param array $productFeatures
     */
    public function setProductFeatures(string $productFeatures): void
    {
        $this->productFeatures = $productFeatures;
    }

    public function getProductFeaturesArray(): ?array
    {
        return json_decode($this->productFeatures,true);
    }

    /**
     * @return mixed
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param mixed $imageFile
     */
    public function setImageFile($imageFile): void
    {
        $this->imageFile = $imageFile;
    }

    /**
     * @return \DateTime
     */
    public function getUploadUpdatedAt(): \DateTime
    {
        return $this->uploadUpdatedAt;
    }

    /**
     * @param \DateTime $uploadUpdatedAt
     */
    public function setUploadUpdatedAt(\DateTime $uploadUpdatedAt): void
    {
        $this->uploadUpdatedAt = $uploadUpdatedAt;
    }

    /**
     * @return int
     */
    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    /**
     * @param int $quantity
     */
    public function setQuantity(int $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * @return Collection|ShopCartItem[]
     */
    public function getShopCartItems(): Collection
    {
        return $this->shopCartItems;
    }

    public function addShopCartItem(ShopCartItem $shopCartItem): self
    {
        if (!$this->shopCartItems->contains($shopCartItem)) {
            $this->shopCartItems[] = $shopCartItem;
            $shopCartItem->setProduct($this);
        }

        return $this;
    }

    /**
     * @return string
     */
    public function getImage(): string
    {
        return $this->image;
    }

    /**
     * @param string $image
     */
    public function setImage(string $image): void
    {
        $this->image = $image;
    }

    /**
     * @return string
     */
    public function getIcon(): string
    {
        return $this->icon;
    }

    /**
     * @param string $icon
     */
    public function setIcon(string $icon): void
    {
        $this->icon = $icon;
    }



    public function removeShopCartItem(ShopCartItem $shopCartItem): self
    {
        if ($this->shopCartItems->contains($shopCartItem)) {
            $this->shopCartItems->removeElement($shopCartItem);
            // set the owning side to null (unless already changed)
            if ($shopCartItem->getProduct() === $this) {
                $shopCartItem->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return bool
     */
    public function isRecommendedProduct(): ?bool
    {
        return $this->recommendedProduct;
    }

    /**
     * @param bool $recommendedProduct
     */
    public function setRecommendedProduct(bool $recommendedProduct): void
    {
        $this->recommendedProduct = $recommendedProduct;
    }

    /**
     * @return mixed
     */
    public function getImageFileBigger()
    {
        return $this->imageFileBigger;
    }

    /**
     * @param mixed $imageFileBigger
     */
    public function setImageFileBigger($imageFileBigger): void
    {
        $this->imageFileBigger = $imageFileBigger;
    }





}

src/Controller/Front/MainController.php
<?php

namespace App\Controller\Front;

use App\Entity\ShopCart;
use App\Entity\ShopCartItem;
use App\Entity\ShopCategory;
use App\Entity\ShopProduct;
use App\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\QueryBuilder;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;
use App\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\ParameterBag;
use Symfony\Component\HttpFoundation\Request;

class MainController extends Controller
{
    protected $searchable = 'e.id e.name';

    public function index(Request $request)
    {
        return $this->render("front/index.html.twig", $this->prepareDefaultParemeters($request));
    }

    public function product(Request $request, $id)
    {
        $array = $this->prepareDefaultParemeters($request);
        /** @var ShopProduct $entity */
        $entity = $this->getDoctrine()->getRepository(ShopProduct::class)->find($id);
        $array['entity'] = $entity;
        return $this->render("front/product.html.twig", $array);
    }

    protected function prepareDefaultParemeters(Request $request)
    {
        /** @var  $categories */
        $categories = $this->getDoctrine()->getRepository(ShopCategory::class)->findBy([
            "parent" => null,
        ]);
        // filter
        $filterFormBuilder = $this->listFilterFormBuilder(['perPage' => 25], $request);
        $filterForm = $filterFormBuilder->getForm();

        $filterForm->handleRequest($request);
        $filterFormData = new ParameterBag();
        if ($filterForm->isSubmitted() && $filterForm->isValid()) {
            $filterFormData->add(array_filter($filterForm->getData()));
            /** @var QueryBuilder $queryBuilder */
            $queryBuilder = $this->getDoctrine()->getRepository(ShopProduct::class)->createQueryBuilder('e');
            //check search...
            if ($filterFormData->has('search') && $filterFormData->get('search')) {
                $searchable = $this->searchable ? explode(' ', $this->searchable) : [];
                $sf = $filterFormData->get('search');
                $sf = '%' . $sf . '%';
                $queryBuilder->setParameter(':search', $sf);
                $whSa = [];
                foreach ($searchable as $field) {
                    $whSa[] = "{$field} LIKE :search";
                }
                $queryBuilder->andWhere(implode(' OR ', $whSa));
            }

            $adapter = new DoctrineORMAdapter($queryBuilder);
            $entities = new Pagerfanta($adapter);
            $entities->setMaxPerPage(9);

            $cpage = $request->get('page');
            if ($cpage <= 0) {
                $cpage = 1;
            } elseif ($cpage > $entities->getNbPages()) {
                $cpage = $entities->getNbPages();
            }

            $entities->setCurrentPage($cpage);

            return [
                "categories" => $categories,
                'filterForm' => $filterForm->createView(),
                'entities' => $entities,
                'type'=> 'standard',
                'cart' => $this->getCartData(),
            ];
        }else {
            /** @var QueryBuilder $queryBuilder */
            $queryBuilder = $this->getDoctrine()->getRepository(ShopProduct::class)->createQueryBuilder('e');
            $queryBuilder->andWhere('e.recommendedProduct = :param');
            $queryBuilder->setParameter(':param', 1);
            $adapter = new DoctrineORMAdapter($queryBuilder);
            $entities = new Pagerfanta($adapter);
            $entities->setMaxPerPage(9);
            return [
                "categories" => $categories,
                'filterForm' => $filterForm->createView(),
                'cart' => $this->getCartData(),
                'type' => 'recommended',
                'entities' => $entities,
            ];
        }
    }

    public function getCartData()
    {
        /** @var ShopCart $data */
        $data = $this->getCartById();
        $data->recalculateData();
        return [
            'total' => $data->getTotalPrice(),
            'itemsCount' => $data->getItemsTotal(),
            'items' => $data->getItems(),
        ];
    }

    public function getCartById()
    {
        if ($this->get('session')->has("shopId")) {
            $data = $this->getDoctrine()->getRepository(ShopCart::class)->find($this->get('session')->get("shopId"));
            if ($data == null) {
                $data = new ShopCart();
            }
            return $data;
        }
        return new ShopCart();
    }

    public function addToCart(Request $request)
    {
        /** @var ShopCart $data */
        $data = $this->getCartById();
        /** @var ShopProduct $product */
        $product = $this->getDoctrine()->getRepository(ShopProduct::class)->find($request->request->get('id'));
        $em = $this->getDoctrine()->getEntityManager();
        $data->addItem($product, $em);
        $data->recalculateData();
        $em->persist($data);
        $em->flush();
        $this->get('session')->set("shopId", $data->getId());
        return new JsonResponse([
            'action' => "Pomyślnie dodano przedmiot do koszyka",
            'currentAmmount' => $data->getItemsTotal(),
        ]);
    }

    public function changeAmount(Request $request)
    {
        /** @var ShopCart $data */
        $data = $this->getCartById();
        /** @var ShopProduct $product */
        $product = $this->getDoctrine()->getRepository(ShopProduct::class)->find($request->request->get('id'));
        $em = $this->getDoctrine()->getEntityManager();
        $newAm = $data->changeAmount($product, $request->request->get("amount"), $em);
        $data->recalculateData();
        $em->persist($data);
        $em->flush();
        $this->get('session')->set("shopId", $data->getId());
        return new JsonResponse(["price" => $data->getTotalPrice(), "quant" => $newAm]);
    }

    public function removeFromCart(Request $request)
    {
        /** @var ShopCart $data */
        $data = $this->getCartById();
        /** @var ShopProduct $product */
        $product = $this->getDoctrine()->getRepository(ShopProduct::class)->find($request->request->get('id'));
        $em = $this->getDoctrine()->getEntityManager();
        $data->removeItem($product, $em);
        $data->recalculateData();
        $em->persist($data);
        $em->flush();

        $this->get('session')->set("shopId", $data->getId());
        return $this->responseAjaxSuccess([
            'action' => "Pomyślnie usunięto przedmiot do koszyka",
            'currentAmmount' => $data->getItemsTotal(),
        ]);
    }

    public function category(Request $request, $category)
    {
        $categories = $this->getDoctrine()->getRepository(ShopCategory::class)->findBy([
            "parent" => null,
        ]);
        $cat = $this->getDoctrine()->getRepository(ShopCategory::class)->findOneBy([
            'name' => $category,
        ]);

        $filterFormBuilder = $this->listFilterFormBuilder(['perPage' => 25], $request);
        $filterForm = $filterFormBuilder->getForm();

        $filterForm->handleRequest($request);
        $filterFormData = new ParameterBag();
        if ($filterForm->isSubmitted() && $filterForm->isValid()) {
            $filterFormData->add(array_filter($filterForm->getData()));
        }

        /** @var QueryBuilder $queryBuilder */
        $queryBuilder = $this->getDoctrine()->getRepository(ShopProduct::class)->createQueryBuilder('e');
        $queryBuilder
            ->andWhere('e.category = :cat')
            ->setParameter(':cat', $cat);
        // pagination

        //check search...
        if ($filterFormData->has('search') && $filterFormData->get('search')) {
            $searchable = $this->searchable ? explode(' ', $this->searchable) : [];
            $sf = $filterFormData->get('search');
            $queryBuilder->setParameter(':search', $sf);
            $sOperator = strpos($sf, '%') !== FALSE ? 'LIKE' : '=';
            $whSa = [];
            foreach ($searchable as $field) {
                $whSa[] = "{$field} {$sOperator} :search";
            }
            $queryBuilder->andWhere(implode(' OR ', $whSa));
        }

        $adapter = new DoctrineORMAdapter($queryBuilder);
        $entities = new Pagerfanta($adapter);
        $entities->setMaxPerPage(9);

        $cpage = $request->get('page');
        if ($cpage <= 0) {
            $cpage = 1;
        } elseif ($cpage > $entities->getNbPages()) {
            $cpage = $entities->getNbPages();
        }

        $entities->setCurrentPage($cpage);

        return $this->render('front/index.html.twig', [
            "categories" => $categories,
            'type'=> 'standard',
            'filterForm' => $filterForm->createView(),
            "entities" => $entities,
        ]);
    }


    public function checkout()
    {
        $categories = $this->getDoctrine()->getRepository(ShopCategory::class)->findBy([
            "parent" => null,
        ]);
        return $this->render('front/checkout.html.twig', [
            'categories' => $categories,
            'cart' => $this->getCartData()
        ]);
    }

    protected function listBuildQuery(QueryBuilder $queryBuilder, Request $request, ParameterBag $filterFormData): void
    {

    }

    protected function listFilterFormBuilder(array $formData, Request $request): FormBuilderInterface
    {
        $formBuilder = $this->createFormBuilderNamed('filter', $formData, [
            'translation_domain' => 'panel',
            'method' => 'GET',
            'csrf_protection' => false,
        ]);
        $formBuilder->add('search', TextType::class, [
            'required' => false,
        ]);
        $formBuilder->add('confirm', SubmitType::class);

templates/front/best_products.html.twig
<div class="wrapper">
    <div class="product-sec1 px-sm-4 px-3 py-sm-5  py-3 mb-4">
        <h3 class="heading-tittle text-center font-italic">Recommended Products</h3>
        <div class="row">
            {% for entity in entities %}
                <div class="col-md-4 product-men mt-5">
                    <div class="men-pro-item simpleCart_shelfItem">
                        <div class="men-thumb-item text-center">
                            {% if entity.image %}
                                <img src="{{ entity.image }}" alt="">
                            {% else %}
                                <img src="{{ asset("build/images/notFound.png") }}">
                            {% endif %}
                            <div class="men-cart-pro">
                                <div class="inner-men-cart-pro">
                                    <a href="{{ path('product', {id: entity.id}) }}" class="link-product-add-cart">Quick
                                        View</a>
                                </div>
                            </div>
                        </div>
                        <div class="item-info-product text-center border-top mt-4">
                            <h4 class="pt-1">
                                <a  href="{{ path('product', {id: entity.id}) }}">{{ entity.name }}</a>
                            </h4>
                            <div class="info-product-price my-2">
                                <span class="item_price">${{ entity.price }}</span>
                            </div>
                            <div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out">
                                <a class="button btn-{{ entity.quantity <= 0 ? "danger" : "primary" }} cartBtn"
                                   data-am="{{ entity.quantity }}"
                                        {{ entity.quantity <=0 ? "disabled" : "" }}
                                   data-id="{{ entity.id }} "> {{ entity.quantity > 0 ? "Add To Cart" : "Out of Stock" }}</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/front/categories.html.twig
<div class="navbar-inner">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto text-center">
                    <li class="nav-item active mr-lg-2 mb-lg-0 mb-2">
                        <a class="nav-link" href="/">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    {% for cat in categories if cat.navbar %}
                        <li class="nav-item dropdown mr-lg-2 mb-lg-0 mb-2">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                {{ cat.name }}
                            </a>
                            <div class="dropdown-menu">
                                <div class="agile_inner_drop_nav_info p-4">
                                    <h5 class="mb-3">{{ cat.name }}</h5>
                                    <div class="row">
                                        {% for sub in cat.children %}
                                            <div class="col-sm-6 multi-gd-img">
                                                <ul class="multi-column-dropdown">
                                                    <a class="cat"
                                                       style="text-decoration: none"
                                                       href="{{ path('front_category', {'category': sub.name}) }}"> {{ sub.name }}</a>
                                                </ul>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                        {% if app.token.user.superadmin %}
                            <li class="nav-item">
                                <a href="{{ path('panel_dashboard') }}" class="nav-link">
                                    Administration Panel </a>
                            </li>
                        {% endif %}
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>
</div>
<style>
    .cat {
        color: black;
        text-decoration: none;
    }

    .cat hover {
        text-decoration: none;
        color: #0c5460;
    }
</style>

templates/front/index.html.twig
{% extends 'base.html.twig' %}
{% trans_default_domain "front" %}
{% block styles %}
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i&amp;subset=latin-ext"
          rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese"
          rel="stylesheet">

{% endblock %}
{% block content %}
    {{ include('front/search_cart.html.twig') }}
    {{ include('front/categories.html.twig') }}
    <div class="ads-grid py-sm-5 py-4">
        <div class="container py-xl-4 py-lg-2">
            <h3 class="title-1 text-center mb-lg-5 mb-sm-4 mb-3">Products</h3>
            <div class="row">
                <div class="agileinfo-ads-display col-lg-9">
                    {% if type == "standard" %}
                        {{ include('front/products.html.twig') }}
                   {% else %}
                        {{ include('front/best_products.html.twig') }}
                    {% endif %}
                </div>
                <div class="col-lg-3 mt-lg-0 mt-4 p-lg-0">
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}

    <script>
        $(".cartBtn").click(function (e) {
            var id = $(this).data('id');
            e.preventDefault();
            console.log(id);
            $.ajax({
                type: 'POST',
                data: {
                    id: id
                },
                url: "{{ path('addToCart') }}",
                dataType: 'json',
                success: function (dataAjax) {
                    toastr.success(dataAjax.action);
                    $("#cartAmmount").html(dataAjax.currentAmmount);
                    console.log(dataAjax);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.status);
                    alert(thrownError);
                }
            });
            //alert($(this).data('id'));
        });
    </script>
    {#<script src="/assets/js/minicart.js"></script>#}
    {#<script>#}
    {#paypals.minicarts.render();#}
    {#// </script>#}
{% endblock %}

templates/front/product.html.twig
{% extends 'base.html.twig' %}
{% block styles %}
    {{ parent() }}
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i&amp;subset=latin-ext"
          rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese"
          rel="stylesheet">


{% endblock %}

{% block content %}
    {{ include('front/categories.html.twig') }}

    <div class="banner py-5">
        <div class="container py-xl-4 py-lg-2">
            <div class="row">
                <div class="col-lg-5 col-md-8 single-right-left ">
                    {% if entity.icon %}
                        <img src="{{ entity.icon }}" alt="">
                    {% else %}
                        <img src="{{ asset("build/images/notFound.png") }}">
                    {% endif %}
                    <div class="clearfix"></div>
                </div>

                <div class="col-lg-7 single-right-left simpleCart_shelfItem">
                    <h3 class="mb-3">{{ entity.name }}</h3>
                    <p class="mb-3">
                        <span class="item_price">${{ entity.price }}</span>
                    </p>
                    Specification
                    <div class="table-responsive-sm">
                        <table>
                            <caption>Information About Product</caption>
                            <tbody>
                            <tr>
                                <th style="width: 10%" scope="row"> Producer</th>
                                <td></td>
                                <td style="width: 70%">{{ entity.producent }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Price</th>
                                <td></td>
                                <td>{{ entity.price }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Short Description</th>
                                <td></td>
                                <td>{{ entity.description }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Available quantity</th>
                                <td></td>
                                <td>{{ entity.quantity }}</td>
                            </tr>
                            <tr></tr>
                            {% for key,value in entity.productFeaturesArray %}
                                <tr>
                                    <th scope="row">{{ key }}</th>
                                    <td></td>
                                    <td>{{ value }}</td>
                                </tr>
                                <tr> <th scope="row"></th></tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    <div class="occasion-cart">
                        <div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out">
                            <a class="button btn-{{ entity.quantity <= 0 ? "danger" : "primary" }} cartBtn"
                               data-am="{{ entity.quantity }}"
                                    {{ entity.quantity <=0 ? "disabled" : "" }}
                               data-id="{{ entity.id }} "> {{ entity.quantity > 0 ? "Add To Cart" : "Out of Stock" }}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}

    <script>
        $(".cartBtn").click(function (e) {
            var id = $(this).data('id');
            e.preventDefault();
            if ($(this).data('am') <= 0) {
                return;
            }
            $.ajax({
                type: 'POST',
                data: {
                    id: id
                },
                url: "{{ path('addToCart') }}",
                dataType: 'json',
                success: function (dataAjax) {
                    toastr.success(dataAjax.action);
                    $("#cartAmmount").html(dataAjax.currentAmmount);
                    console.log(dataAjax);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.status);
                    alert(thrownError);
                }
            });
            //alert($(this).data('id'));
        });
    </script>
{% endblock %}